// src/main/webapp/app/entities/shop/shop-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './shop.reducer';

export const ShopDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const shopEntity = useAppSelector(state => state.shop.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="shopDetailsHeading">
          <Translate contentKey="coopcycleApp.shop.detail.title">Shop</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{shopEntity.id}</dd>
          <dt>
            <span id="addressS">
              <Translate contentKey="coopcycleApp.shop.addressS">Address S</Translate>
            </span>
          </dt>
          <dd>{shopEntity.addressS}</dd>
          <dt>
            <span id="menu">
              <Translate contentKey="coopcycleApp.shop.menu">Menu</Translate>
            </span>
          </dt>
          <dd>{shopEntity.menu}</dd>
        </dl>
        <Button tag={Link} to="/shop" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/shop/${shopEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ShopDetail;

// src/main/webapp/app/entities/shop/detail/shop-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IShop } from '../shop.model';

@Component({
  selector: 'jhi-shop-detail',
  templateUrl: './shop-detail.component.html',
})
export class ShopDetailComponent implements OnInit {
  shop: IShop | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ shop }) => {
      this.shop = shop;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="shop">
      <h2 data-cy="shopDetailsHeading"><span jhiTranslate="coopcyclejhipsterApp.shop.detail.title">Shop</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ shop.id }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.shop.addressS">Address S</span></dt>
        <dd>
          <span>{{ shop.addressS }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.shop.menu">Menu</span></dt>
        <dd>
          <span>{{ shop.menu }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/shop', shop.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
