// src/main/webapp/app/entities/cooperative/list/cooperative.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ICooperative } from '../cooperative.model';
import { CooperativeService } from '../service/cooperative.service';
import { CooperativeDeleteDialogComponent } from '../delete/cooperative-delete-dialog.component';

@Component({
  selector: 'jhi-cooperative',
  templateUrl: './cooperative.component.html',
})
export class CooperativeComponent implements OnInit {
  cooperatives?: ICooperative[];
  isLoading = false;

  constructor(protected cooperativeService: CooperativeService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.cooperativeService.query().subscribe({
      next: (res: HttpResponse<ICooperative[]>) => {
        this.isLoading = false;
        this.cooperatives = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(_index: number, item: ICooperative): string {
    return item.id!;
  }

  delete(cooperative: ICooperative): void {
    const modalRef = this.modalService.open(CooperativeDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.cooperative = cooperative;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="CooperativeHeading">
    <span jhiTranslate="coopcyclejhipsterApp.cooperative.home.title">Cooperatives</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.cooperative.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-cooperative"
        [routerLink]="['/cooperative/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.cooperative.home.createLabel"> Create a new Cooperative </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="cooperatives?.length === 0">
    <span jhiTranslate="coopcyclejhipsterApp.cooperative.home.notFound">No cooperatives found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="cooperatives && cooperatives.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.cooperative.id">Id</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.cooperative.name">Name</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let cooperative of cooperatives; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/cooperative', cooperative.id, 'view']">{{ cooperative.id }}</a>
          </td>
          <td>{{ cooperative.name }}</td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/cooperative', cooperative.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/cooperative', cooperative.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(cooperative)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/cooperative/cooperative.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ICooperative } from 'app/shared/model/cooperative.model';
import { getEntities } from './cooperative.reducer';

export const Cooperative = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const cooperativeList = useAppSelector(state => state.cooperative.entities);
  const loading = useAppSelector(state => state.cooperative.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="cooperative-heading" data-cy="CooperativeHeading">
        <Translate contentKey="coopcycleApp.cooperative.home.title">Cooperatives</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="coopcycleApp.cooperative.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/cooperative/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="coopcycleApp.cooperative.home.createLabel">Create new Cooperative</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {cooperativeList && cooperativeList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="coopcycleApp.cooperative.id">Id</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.cooperative.name">Name</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {cooperativeList.map((cooperative, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/cooperative/${cooperative.id}`} color="link" size="sm">
                      {cooperative.id}
                    </Button>
                  </td>
                  <td>{cooperative.name}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/cooperative/${cooperative.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/cooperative/${cooperative.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/cooperative/${cooperative.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="coopcycleApp.cooperative.home.notFound">No Cooperatives found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Cooperative;
