// src/main/webapp/app/entities/driver/driver-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './driver.reducer';

export const DriverDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const driverEntity = useAppSelector(state => state.driver.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="driverDetailsHeading">
          <Translate contentKey="coopcycleApp.driver.detail.title">Driver</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{driverEntity.id}</dd>
          <dt>
            <span id="firstnameD">
              <Translate contentKey="coopcycleApp.driver.firstnameD">Firstname D</Translate>
            </span>
          </dt>
          <dd>{driverEntity.firstnameD}</dd>
          <dt>
            <span id="lastnameD">
              <Translate contentKey="coopcycleApp.driver.lastnameD">Lastname D</Translate>
            </span>
          </dt>
          <dd>{driverEntity.lastnameD}</dd>
          <dt>
            <span id="phoneD">
              <Translate contentKey="coopcycleApp.driver.phoneD">Phone D</Translate>
            </span>
          </dt>
          <dd>{driverEntity.phoneD}</dd>
          <dt>
            <Translate contentKey="coopcycleApp.driver.cooperative">Cooperative</Translate>
          </dt>
          <dd>{driverEntity.cooperative ? driverEntity.cooperative.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/driver" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/driver/${driverEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default DriverDetail;

// src/main/webapp/app/entities/driver/detail/driver-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IDriver } from '../driver.model';

@Component({
  selector: 'jhi-driver-detail',
  templateUrl: './driver-detail.component.html',
})
export class DriverDetailComponent implements OnInit {
  driver: IDriver | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ driver }) => {
      this.driver = driver;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="driver">
      <h2 data-cy="driverDetailsHeading"><span jhiTranslate="coopcyclejhipsterApp.driver.detail.title">Driver</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ driver.id }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.driver.firstnameD">Firstname D</span></dt>
        <dd>
          <span>{{ driver.firstnameD }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.driver.lastnameD">Lastname D</span></dt>
        <dd>
          <span>{{ driver.lastnameD }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.driver.phoneD">Phone D</span></dt>
        <dd>
          <span>{{ driver.phoneD }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.driver.cooperative">Cooperative</span></dt>
        <dd>
          <div *ngIf="driver.cooperative">
            <a [routerLink]="['/cooperative', driver.cooperative?.id, 'view']">{{ driver.cooperative?.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/driver', driver.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
