// src/main/webapp/app/entities/command/list/command.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ICommand } from '../command.model';
import { CommandService } from '../service/command.service';
import { CommandDeleteDialogComponent } from '../delete/command-delete-dialog.component';

@Component({
  selector: 'jhi-command',
  templateUrl: './command.component.html',
})
export class CommandComponent implements OnInit {
  commands?: ICommand[];
  isLoading = false;

  constructor(protected commandService: CommandService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.commandService.query().subscribe({
      next: (res: HttpResponse<ICommand[]>) => {
        this.isLoading = false;
        this.commands = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(_index: number, item: ICommand): number {
    return item.id!;
  }

  delete(command: ICommand): void {
    const modalRef = this.modalService.open(CommandDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.command = command;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="CommandHeading">
    <span jhiTranslate="coopcyclejhipsterApp.command.home.title">Commands</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.command.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-command"
        [routerLink]="['/command/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.command.home.createLabel"> Create a new Command </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="commands?.length === 0">
    <span jhiTranslate="coopcyclejhipsterApp.command.home.notFound">No commands found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="commands && commands.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.command.addressC">Address C</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.command.dateC">Date C</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.command.client">Client</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.command.driver">Driver</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let command of commands; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/command', command.id, 'view']">{{ command.id }}</a>
          </td>
          <td>{{ command.addressC }}</td>
          <td>{{ command.dateC }}</td>
          <td>
            <div *ngIf="command.client">
              <a [routerLink]="['/client', command.client?.id, 'view']">{{ command.client?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="command.driver">
              <a [routerLink]="['/driver', command.driver?.id, 'view']">{{ command.driver?.id }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/command', command.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/command', command.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(command)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/command/command.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ICommand } from 'app/shared/model/command.model';
import { getEntities } from './command.reducer';

export const Command = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const commandList = useAppSelector(state => state.command.entities);
  const loading = useAppSelector(state => state.command.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="command-heading" data-cy="CommandHeading">
        <Translate contentKey="coopcycleApp.command.home.title">Commands</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="coopcycleApp.command.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/command/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="coopcycleApp.command.home.createLabel">Create new Command</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {commandList && commandList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="coopcycleApp.command.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.command.addressC">Address C</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.command.dateC">Date C</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.command.client">Client</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.command.driver">Driver</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {commandList.map((command, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/command/${command.id}`} color="link" size="sm">
                      {command.id}
                    </Button>
                  </td>
                  <td>{command.addressC}</td>
                  <td>{command.dateC}</td>
                  <td>{command.client ? <Link to={`/client/${command.client.id}`}>{command.client.id}</Link> : ''}</td>
                  <td>{command.driver ? <Link to={`/driver/${command.driver.id}`}>{command.driver.id}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/command/${command.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/command/${command.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/command/${command.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="coopcycleApp.command.home.notFound">No Commands found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Command;
