// src/main/webapp/app/entities/command/detail/command-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ICommand } from '../command.model';

@Component({
  selector: 'jhi-command-detail',
  templateUrl: './command-detail.component.html',
})
export class CommandDetailComponent implements OnInit {
  command: ICommand | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ command }) => {
      this.command = command;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="command">
      <h2 data-cy="commandDetailsHeading"><span jhiTranslate="coopcyclejhipsterApp.command.detail.title">Command</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ command.id }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.command.addressC">Address C</span></dt>
        <dd>
          <span>{{ command.addressC }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.command.dateC">Date C</span></dt>
        <dd>
          <span>{{ command.dateC }}</span>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.command.client">Client</span></dt>
        <dd>
          <div *ngIf="command.client">
            <a [routerLink]="['/client', command.client?.id, 'view']">{{ command.client?.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="coopcyclejhipsterApp.command.driver">Driver</span></dt>
        <dd>
          <div *ngIf="command.driver">
            <a [routerLink]="['/driver', command.driver?.id, 'view']">{{ command.driver?.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/command', command.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/command/command-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './command.reducer';

export const CommandDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const commandEntity = useAppSelector(state => state.command.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="commandDetailsHeading">
          <Translate contentKey="coopcycleApp.command.detail.title">Command</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{commandEntity.id}</dd>
          <dt>
            <span id="addressC">
              <Translate contentKey="coopcycleApp.command.addressC">Address C</Translate>
            </span>
          </dt>
          <dd>{commandEntity.addressC}</dd>
          <dt>
            <span id="dateC">
              <Translate contentKey="coopcycleApp.command.dateC">Date C</Translate>
            </span>
          </dt>
          <dd>{commandEntity.dateC}</dd>
          <dt>
            <Translate contentKey="coopcycleApp.command.client">Client</Translate>
          </dt>
          <dd>{commandEntity.client ? commandEntity.client.id : ''}</dd>
          <dt>
            <Translate contentKey="coopcycleApp.command.driver">Driver</Translate>
          </dt>
          <dd>{commandEntity.driver ? commandEntity.driver.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/command" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/command/${commandEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CommandDetail;
