// src/main/webapp/app/entities/driver/list/driver.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IDriver } from '../driver.model';
import { DriverService } from '../service/driver.service';
import { DriverDeleteDialogComponent } from '../delete/driver-delete-dialog.component';

@Component({
  selector: 'jhi-driver',
  templateUrl: './driver.component.html',
})
export class DriverComponent implements OnInit {
  drivers?: IDriver[];
  isLoading = false;

  constructor(protected driverService: DriverService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.driverService.query().subscribe({
      next: (res: HttpResponse<IDriver[]>) => {
        this.isLoading = false;
        this.drivers = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(_index: number, item: IDriver): number {
    return item.id!;
  }

  delete(driver: IDriver): void {
    const modalRef = this.modalService.open(DriverDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.driver = driver;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="DriverHeading">
    <span jhiTranslate="coopcyclejhipsterApp.driver.home.title">Drivers</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.driver.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-driver"
        [routerLink]="['/driver/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="coopcyclejhipsterApp.driver.home.createLabel"> Create a new Driver </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="drivers?.length === 0">
    <span jhiTranslate="coopcyclejhipsterApp.driver.home.notFound">No drivers found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="drivers && drivers.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.driver.firstnameD">Firstname D</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.driver.lastnameD">Lastname D</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.driver.phoneD">Phone D</span></th>
          <th scope="col"><span jhiTranslate="coopcyclejhipsterApp.driver.cooperative">Cooperative</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let driver of drivers; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/driver', driver.id, 'view']">{{ driver.id }}</a>
          </td>
          <td>{{ driver.firstnameD }}</td>
          <td>{{ driver.lastnameD }}</td>
          <td>{{ driver.phoneD }}</td>
          <td>
            <div *ngIf="driver.cooperative">
              <a [routerLink]="['/cooperative', driver.cooperative?.id, 'view']">{{ driver.cooperative?.id }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/driver', driver.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/driver', driver.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(driver)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/driver/driver.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDriver } from 'app/shared/model/driver.model';
import { getEntities } from './driver.reducer';

export const Driver = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const driverList = useAppSelector(state => state.driver.entities);
  const loading = useAppSelector(state => state.driver.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="driver-heading" data-cy="DriverHeading">
        <Translate contentKey="coopcycleApp.driver.home.title">Drivers</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="coopcycleApp.driver.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/driver/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="coopcycleApp.driver.home.createLabel">Create new Driver</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {driverList && driverList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="coopcycleApp.driver.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.driver.firstnameD">Firstname D</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.driver.lastnameD">Lastname D</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.driver.phoneD">Phone D</Translate>
                </th>
                <th>
                  <Translate contentKey="coopcycleApp.driver.cooperative">Cooperative</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {driverList.map((driver, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/driver/${driver.id}`} color="link" size="sm">
                      {driver.id}
                    </Button>
                  </td>
                  <td>{driver.firstnameD}</td>
                  <td>{driver.lastnameD}</td>
                  <td>{driver.phoneD}</td>
                  <td>{driver.cooperative ? <Link to={`/cooperative/${driver.cooperative.id}`}>{driver.cooperative.id}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/driver/${driver.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/driver/${driver.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/driver/${driver.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="coopcycleApp.driver.home.notFound">No Drivers found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Driver;
